Algoritmo "terreno"



Var
   largura, comprimento, valorm, area, preco : real



Inicio
      escreval("Digite a largura do terreno:")
      leia(largura)
      escreval("Digite o comprimento do terreno:")
      leia(comprimento)
      escreval("Digite o valor do metro quadrado:")
      leia(valorm)
      area := largura*comprimento
      preco := area*valorm
      escreval("Area do terreno =", area)
      escreval("Preco do terreno =", preco)




Fimalgoritmo